name: Flutter Build Workflow for iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macOS-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Flutter
        run: |
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_3.7.12-stable.zip
          unzip flutter_macos_3.7.12-stable.zip -d $HOME
          echo "$HOME/flutter/bin" >> $GITHUB_PATH

      - name: Set up CocoaPods
        run: |
          sudo gem install cocoapods
          pod setup

      - name: Check Flutter Version and Doctor Output
        run: |
          flutter --version
          flutter doctor
          flutter pub get

      - name: Install Pods
        run: |
          cd ios
          pod install
          
      - name: Build IPA
        run: |
          flutter build ipa --release --no-codesign

      - name: Archive Built IPA
        uses: actions/upload-artifact@v3
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Copy iOS App to VM
        run: |
          ls ./build/ios/iphoneos
          scp -o StrictHostKeyChecking=no ./build/ios/ipa/*.ipa azureuser@172.191.161.66:/var/www

      - name: Connect to VM and Execute Commands
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@172.191.161.66 "echo 'iOS app uploaded successfully'"

      # The steps for setting up SSH and copying the app to a VM are removed
      # since typically IPA files are not deployed directly to a web server.
