name: Flutter Build Workflow for iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macOS-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Flutter
        run: |
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_3.7.12-stable.zip
          unzip flutter_macos_3.7.12-stable.zip -d $HOME
          echo "$HOME/flutter/bin" >> $GITHUB_PATH

      - name: Check Flutter Version and Doctor Output
        run: |
          flutter --version
          flutter doctor
          flutter pub get

      - name: Build iOS
        run: |
          flutter build ios --release --no-codesign

      - name: Archive Built iOS App
        uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: build/ios/iphoneos/*.app

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Copy iOS App to VM
        run: |
          scp -o StrictHostKeyChecking=no ./build/ios/iphoneos/winplazza.app azureuser@172.191.161.66:/var/www

      - name: Connect to VM and Execute Commands
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@172.191.161.66 "echo 'iOS app uploaded successfully'"
