name: Flutter Build for Android and iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macOS-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Flutter
        run: |
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_3.7.12-stable.zip
          unzip flutter_macos_3.7.12-stable.zip -d $HOME
          echo "$HOME/flutter/bin" >> $GITHUB_PATH

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_13.4.app

      - name: Set up CocoaPods
        run: |
          sudo gem install cocoapods
          pod setup

      - name: Check Flutter Version and Doctor Output
        run: |
          flutter --version
          flutter doctor
          flutter pub get

      - name: Install Pods
        run: |
          cd ios
          pod install

      - name: Install Fastlane
        run: |
          brew install fastlane
      
      - name: Fastlane Build and Sign
        env:
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
        run: |
          cd ios
          fastlane ios build_and_export_ipa

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Copy iOS App to VM
        run: |
          scp -o StrictHostKeyChecking=no ./build/ios/iphoneos/*.ipa azureuser@172.191.161.66:/var/www

      - name: Connect to VM and Execute Commands
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@172.191.161.66 "echo 'iOS app uploaded successfully'"
